name: Rollbar deploy
  uses: rollbar/github-deploy-action@2.1.2
  with:
    environment: 'production'
    version: ${{ github.sha }}
  env:
    ROLLBAR_ACCESS_TOKEN: '867a5b69114644f0a4b4e68a0bd4972f'
    ROLLBAR_USERNAME: 'thedevfactory'
    LOCAL_USERNAME: 'TheDevFactory'
