name: Rollbar deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  uses: rollbar/github-deploy-action@2.1.2  
  with:
    environment: 'production'
    version: ${{ github.sha }}
  env:
    ROLLBAR_ACCESS_TOKEN: '867a5b69114644f0a4b4e68a0bd4972f'
    ROLLBAR_USERNAME: 'thedevfactory'
    LOCAL_USERNAME: 'TheDevFactory'
